on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: R-CMD-check

# https://ropenscilabs.github.io/actions_sandbox/testing-with-renev.html

jobs:
  R-CMD-check:
    runs-on: ubuntu-18.04
    run: |
      echo "R_VERSION=4.04" >> $GITHUB_ENV
    steps:
      - uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: env.R_VERSION
      - name: Install libcurl
        run: sudo apt-get install libcurl4-openssl-dev libv8-dev libgit2-dev
      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-{{env.R_VERSION}}-${{ hashFiles('depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-{{env.R_VERSION}}-
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "curl"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
